config/routes.rb
Drywall::Application.routes.draw do |map|
  
  devise_for :users
  
  root :to => "things#index"

  resources :list

  resources :category

  resources :source

  resources :thing
  
  resources :tag
  
  resources :setting

end

app/models/source.rb
class Source
  include MongoMapper::Document
  
  key :feed_urls, Array
  key :count, Integer
  key :home_url, String
  key :name, String
  key :slug, String
  key :description, String
  key :tags, Array
  timestamps!
  
  many :things, :dependent => :destroy
  many :categories 
  
  after_create :delayed_fetch
  
  def last_thing
    things.first(:order => "created_at DESC")
  end
  
  def to_param
    slug
  end
  
  def fetch
    feed_urls.each do |f|
      Fetch.single(f, self)
    end
  end
  
  
  def delayed_fetch
    self.send_later(:fetch)
  end
  
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_filter :find_source, :only => [:show, :edit, :destroy]
  load_and_authorize_resource
  
  # GET /sources
  # GET /sources.xml
  def index
    @sources = Source.paginate(:page => page, :per_page => 10, :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.xml
  def show
    
    @things = @source.things.paginate(:page => page, :per_page => Setting.articles_per_page, :order => "created_at DESC")
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.xml
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.xml
  def create
    unless params[:source][:categories].blank?
      params[:source][:categories] = params[:source][:categories].split(",").collect{|u| u.strip}.reject{|u| u.blank?}.uniq.collect{|p| Category.new(:name => p)}
    end
    unless params[:source][:feed_urls].blank?
      params[:source][:feed_urls] = params[:source][:feed_urls].split(",").collect{|u| u.strip}.reject{|u| u.blank?}.uniq
    end
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        format.html { redirect_to(@source, :notice => 'Source was successfully created. We\'ll be doing an initial fetch of articles shortly.') }
        format.xml  { render :xml => @source, :status => :created, :location => @source }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.xml
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html { redirect_to(@source, :notice => 'Source was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.xml
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to(sources_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def find_source
    @source = Source.first(:slug => params[:id])
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<% semantic_form_for(@source) do |f| %>
  <% f.inputs :name => 'Source' do %>
    <%= f.input :slug, :label => 'slug' %>
    <%= f.input :name, :label => 'name' %>
    <%= f.input :description, :label => 'Description' %>
    <%= f.input :home_url, :label => 'Home URL' %>
    <%= f.input :feed_urls, :label => 'Feed URLs' %>
    <%= f.input :categories, :label => 'Categories' %>
    <%= f.commit_button 'Submit' %>
  <% end %>
  
<% end %>

app/views/sources/_source.html.erb
<h6><%= link_to source.name, source_url(source) %></h6>
<p class="summary"><%= source.description %></p>
<p class="meta"><%= link_to "Homepage", source.home_url %> :: <%= source.things.count %> items<% unless source.last_thing.blank? %> :: <%= time_ago_in_words(source.last_thing.created_at) %> ago<% end %><% unless source.categories.blank? %> :: Categories: <%= source.categories.collect{|u| link_to u.name, category_url(u)}.to_sentence.html_safe %><% end %></p>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<%= will_paginate(@sources) %>

<%= render :partial => "source", :collection => @sources %>

<%= will_paginate(@sources) %>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<%= will_paginate(@things) %>

<%= render :partial => "things/thing", :collection => @things %>

<%= will_paginate(@things) %>

<%= link_to 'Edit', edit_source_path(@source) if can?(:update, @source) %>